### PR TITLE
update to version 3.1.1

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by sannykr** [comment]
@dougalsutherland : Can I make it a noarch?

**Comment by djsutherland** [comment]
@sannykr Yep, should be fine.

**Comment by djsutherland** [comment]
@conda-forge-admin, please rerender.

**Comment by sannykr** [comment]
@dougalsutherland : Thanks.  I will make sure I rerender if I make a package noarch.

**Comment by djsutherland** [comment]
Yep, any kind of change like that needs a rerender. Though you can actually just say (with an @ at the start) ["conda-forge-admin, please add noarch: python"](https://conda-forge.org/docs/webservice.html#conda-forge-admin-please-add-noarch-python) and it'll do both for you. :)

**Pull request merged**
